# Generated by Django 2.2.6 on 2019-10-09 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0002_auto_20191009_0911'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyecto',
            name='desecripcion',
        ),
        migrations.AddField(
            model_name='proyecto',
            name='Completo',
            field=models.BooleanField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proyecto',
            name='Grupo',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
    ]
