# Generated by Django 2.2.6 on 2019-10-09 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0003_auto_20191009_0914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='tiempo',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
